server:
  port: 3000

spring:
  # 데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: PROJECT_BOARD
    password: _aA123456

  sql:
    init:
      mode: always

    #파일 업로드 설정
  servlet:
    multipart:
      maxFile-size: 20MB
      maxRequestSize: 40MB

  # 정적 자원 설정 css js 이미지
  resources:
    staticLocations:file:src/main/resources/static/

  # 라이브 리로드 설정
  devtools:
    livereloads:
      enabled: true
  #타임리프 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  flyway:
    enabled: true





file:
  upload:
    path: C:/uploads/
    url: /uploads/





# 로거 설정
logging:
  level:
    org:
      springframework:
        jdbc: trace
